# Generated by Django 5.2.8 on 2025-11-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_cn",
                    models.CharField(
                        max_length=100, verbose_name="中文名称 | Chinese Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, verbose_name="英文名称 | English Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL标识 | URL Slug"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序 | Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "文章分类 | Article Category",
                "verbose_name_plural": "文章分类 | Article Categories",
                "ordering": ["order", "name_cn"],
            },
        ),
        migrations.CreateModel(
            name="ClinicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_name_cn",
                    models.CharField(
                        max_length=200,
                        verbose_name="诊所名称（中文） | Clinic Name (Chinese)",
                    ),
                ),
                (
                    "clinic_name_en",
                    models.CharField(
                        max_length=200,
                        verbose_name="诊所名称（英文） | Clinic Name (English)",
                    ),
                ),
                (
                    "tagline_cn",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="标语（中文） | Tagline (Chinese)",
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="标语（英文） | Tagline (English)",
                    ),
                ),
                (
                    "about_cn",
                    models.TextField(
                        blank=True, verbose_name="关于我们（中文） | About Us (Chinese)"
                    ),
                ),
                (
                    "about_en",
                    models.TextField(
                        blank=True, verbose_name="关于我们（英文） | About Us (English)"
                    ),
                ),
                ("address", models.TextField(verbose_name="地址 | Address")),
                ("phone", models.CharField(max_length=50, verbose_name="电话 | Phone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="邮箱 | Email"
                    ),
                ),
                (
                    "business_hours_cn",
                    models.TextField(
                        help_text="例如：周一至周六 9:00-18:00",
                        verbose_name="营业时间（中文） | Business Hours (Chinese)",
                    ),
                ),
                (
                    "business_hours_en",
                    models.TextField(
                        help_text="e.g.: Mon-Sat 9:00-18:00",
                        verbose_name="营业时间（英文） | Business Hours (English)",
                    ),
                ),
                (
                    "google_maps_embed",
                    models.TextField(
                        blank=True,
                        help_text="从Google Maps复制iframe代码 | Copy iframe code from Google Maps",
                        verbose_name="Google地图嵌入代码 | Google Maps Embed Code",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, verbose_name="Facebook链接 | Facebook URL"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, verbose_name="Instagram链接 | Instagram URL"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="包含国家代码，例如：60123456789",
                        max_length=50,
                        verbose_name="WhatsApp号码 | WhatsApp Number",
                    ),
                ),
                (
                    "wechat_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="微信号 | WeChat ID"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clinic/",
                        verbose_name="诊所Logo | Clinic Logo",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clinic/",
                        verbose_name="首页主图 | Hero Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所信息 | Clinic Information",
                "verbose_name_plural": "诊所信息 | Clinic Information",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_cn",
                    models.CharField(
                        max_length=200, verbose_name="中文名称 | Chinese Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="英文名称 | English Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL标识 | URL Slug"
                    ),
                ),
                (
                    "description_cn",
                    models.TextField(verbose_name="中文描述 | Chinese Description"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="英文描述 | English Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-circle",
                        help_text="Bootstrap Icon class (e.g., bi-heart-pulse)",
                        max_length=100,
                        verbose_name="图标 | Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="图片 | Image",
                    ),
                ),
                (
                    "price_info_cn",
                    models.CharField(
                        blank=True,
                        help_text="例如：RM 80 - RM 150",
                        max_length=200,
                        verbose_name="价格信息（中文） | Price Info (Chinese)",
                    ),
                ),
                (
                    "price_info_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g.: RM 80 - RM 150",
                        max_length=200,
                        verbose_name="价格信息（英文） | Price Info (English)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="数字越小越靠前 | Lower numbers appear first",
                        verbose_name="排序 | Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "服务项目 | Service",
                "verbose_name_plural": "服务项目 | Services",
                "ordering": ["order", "name_cn"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        help_text="可以使用化名 | Can use pseudonym",
                        max_length=100,
                        verbose_name="患者姓名 | Patient Name",
                    ),
                ),
                (
                    "content_cn",
                    models.TextField(
                        blank=True, verbose_name="评价内容（中文） | Content (Chinese)"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True, verbose_name="评价内容（英文） | Content (English)"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ (5)"),
                            (4, "⭐⭐⭐⭐ (4)"),
                            (3, "⭐⭐⭐ (3)"),
                            (2, "⭐⭐ (2)"),
                            (1, "⭐ (1)"),
                        ],
                        default=5,
                        verbose_name="评分 | Rating",
                    ),
                ),
                (
                    "service_received",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="接受的服务 | Service Received",
                    ),
                ),
                (
                    "testimonial_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="评价日期 | Testimonial Date"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="只有审核通过的评价才会显示在网站上 | Only approved testimonials appear on website",
                        verbose_name="已审核 | Approved",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="精选评价会显示在首页 | Featured testimonials appear on homepage",
                        verbose_name="精选 | Featured",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序 | Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "患者评价 | Testimonial",
                "verbose_name_plural": "患者评价 | Testimonials",
                "ordering": ["-is_featured", "order", "-testimonial_date"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_cn",
                    models.CharField(
                        max_length=300, verbose_name="中文标题 | Chinese Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=300, verbose_name="英文标题 | English Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=300, unique=True, verbose_name="URL标识 | URL Slug"
                    ),
                ),
                (
                    "summary_cn",
                    models.TextField(
                        blank=True,
                        help_text="简短摘要，用于列表页显示",
                        verbose_name="中文摘要 | Chinese Summary",
                    ),
                ),
                (
                    "summary_en",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary for list pages",
                        verbose_name="英文摘要 | English Summary",
                    ),
                ),
                (
                    "content_cn",
                    models.TextField(verbose_name="中文内容 | Chinese Content"),
                ),
                (
                    "content_en",
                    models.TextField(verbose_name="英文内容 | English Content"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="特色图片 | Featured Image",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布日期 | Published Date"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="已发布 | Published"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="精选文章会显示在首页 | Featured articles appear on homepage",
                        verbose_name="精选 | Featured",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, verbose_name="浏览次数 | Views Count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "practitioner"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者 | Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="website.articlecategory",
                        verbose_name="分类 | Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康文章 | Article",
                "verbose_name_plural": "健康文章 | Articles",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
