# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_medicalhistorytimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuppingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=50, verbose_name='中文名称 | Chinese Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称 | English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('description', models.TextField(blank=True, verbose_name='描述 | Description')),
                ('method', models.TextField(blank=True, help_text='详细操作步骤 | Detailed operation steps', verbose_name='操作方法 | Method')),
                ('indications', models.TextField(blank=True, verbose_name='适应症 | Indications')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌症 | Contraindications')),
                ('precautions', models.TextField(blank=True, verbose_name='注意事项 | Precautions')),
                ('typical_duration', models.IntegerField(default=10, verbose_name='典型时长(分钟) | Typical Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '拔罐手法 | Cupping Technique',
                'verbose_name_plural': '拔罐手法 | Cupping Techniques',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='CuppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(verbose_name='治疗日期 | Session Date')),
                ('chief_complaint', models.TextField(verbose_name='主诉 | Chief Complaint')),
                ('tcm_diagnosis', models.TextField(blank=True, verbose_name='中医诊断 | TCM Diagnosis')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='治则 | Treatment Principle')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='治疗时长(分钟) | Duration (minutes)')),
                ('treatment_locations', models.JSONField(default=list, help_text='身体部位列表 | List of body locations treated', verbose_name='治疗部位 | Treatment Locations')),
                ('skin_reaction', models.CharField(blank=True, help_text='例如：淡红、紫红、黑紫、有水泡等', max_length=200, verbose_name='皮肤反应 | Skin Reaction')),
                ('cup_marks_description', models.TextField(blank=True, verbose_name='罐印描述 | Cup Marks Description')),
                ('patient_sensation', models.TextField(blank=True, help_text='治疗过程中和治疗后的感受', verbose_name='患者感受 | Patient Sensation')),
                ('pain_level_before', models.IntegerField(blank=True, help_text='0-10级，0=无痛，10=剧痛', null=True, verbose_name='治疗前疼痛等级 | Pain Level Before')),
                ('pain_level_after', models.IntegerField(blank=True, help_text='0-10级', null=True, verbose_name='治疗后疼痛等级 | Pain Level After')),
                ('immediate_effect', models.TextField(blank=True, verbose_name='即时效果 | Immediate Effect')),
                ('post_treatment_advice', models.TextField(blank=True, verbose_name='治疗后建议 | Post-Treatment Advice')),
                ('next_session_date', models.DateField(blank=True, null=True, verbose_name='下次治疗日期 | Next Session Date')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件 | Attachments')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupping_sessions', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupping_sessions', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
            ],
            options={
                'verbose_name': '拔罐记录 | Cupping Session',
                'verbose_name_plural': '拔罐记录 | Cupping Sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='CuppingSessionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_location', models.CharField(help_text='例如：背部、肩部、腰部等', max_length=100, verbose_name='治疗部位 | Body Location')),
                ('duration_minutes', models.IntegerField(default=10, verbose_name='时长(分钟) | Duration (minutes)')),
                ('number_of_cups', models.IntegerField(default=1, verbose_name='罐数 | Number of Cups')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注 | Notes')),
                ('sequence', models.IntegerField(default=0, verbose_name='顺序 | Sequence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques_used', to='cupping.cuppingsession', verbose_name='治疗记录 | Session')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_uses', to='cupping.cuppingtechnique', verbose_name='手法 | Technique')),
            ],
            options={
                'verbose_name': '治疗手法记录 | Session Technique',
                'verbose_name_plural': '治疗手法记录 | Session Techniques',
                'ordering': ['sequence', 'technique'],
            },
        ),
    ]
