# Generated by Django 5.2.8 on 2025-11-18 14:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名')),
                ('name_en', models.CharField(max_length=200, verbose_name='English Name')),
                ('name_pinyin', models.CharField(blank=True, max_length=200, verbose_name='拼音')),
                ('source', models.CharField(blank=True, help_text='Classical text source', max_length=200, verbose_name='出处')),
                ('composition', models.TextField(help_text='Original composition description', verbose_name='组成')),
                ('functions', models.TextField(blank=True, verbose_name='功效')),
                ('indications', models.TextField(blank=True, verbose_name='主治')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌')),
                ('modifications', models.TextField(blank=True, help_text='Common modifications', verbose_name='加减变化')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '经典方剂',
                'verbose_name_plural': '经典方剂',
                'ordering': ['name_pinyin', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='HerbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100, verbose_name='名称 (中文)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '药材类别',
                'verbose_name_plural': '药材类别',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名')),
                ('name_en', models.CharField(max_length=200, verbose_name='English Name')),
                ('name_pinyin', models.CharField(blank=True, max_length=200, verbose_name='拼音')),
                ('name_latin', models.CharField(blank=True, max_length=200, verbose_name='拉丁名')),
                ('nature', models.CharField(choices=[('hot', '热 | Hot'), ('warm', '温 | Warm'), ('neutral', '平 | Neutral'), ('cool', '凉 | Cool'), ('cold', '寒 | Cold')], default='neutral', max_length=20, verbose_name='药性')),
                ('taste', models.JSONField(default=list, help_text='List of tastes, e.g., ["sweet", "bitter"]', verbose_name='药味')),
                ('meridians', models.JSONField(default=list, help_text='List of meridians, e.g., ["lung", "spleen"]', verbose_name='归经')),
                ('functions', models.TextField(blank=True, help_text='Main therapeutic functions', verbose_name='功效')),
                ('indications', models.TextField(blank=True, help_text='Clinical indications', verbose_name='主治')),
                ('contraindications', models.TextField(blank=True, help_text='Contraindications and cautions', verbose_name='禁忌')),
                ('dosage_min', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6, verbose_name='最小剂量 (克)')),
                ('dosage_max', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6, verbose_name='最大剂量 (克)')),
                ('dosage_unit', models.CharField(default='克', max_length=20, verbose_name='剂量单位')),
                ('preparation_notes', models.TextField(blank=True, help_text='Special preparation or decoction instructions', verbose_name='炮制/煎煮说明')),
                ('price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='单价 (每克)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_toxic', models.BooleanField(default=False, verbose_name='有毒')),
                ('requires_processing', models.BooleanField(default=False, verbose_name='需炮制')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herbs', to='prescriptions.herbcategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '中药',
                'verbose_name_plural': '中药',
                'ordering': ['name_pinyin', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=50, unique=True, verbose_name='处方编号')),
                ('prescription_date', models.DateTimeField(auto_now_add=True, verbose_name='处方日期')),
                ('diagnosis', models.TextField(blank=True, verbose_name='诊断')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='治则治法')),
                ('doses', models.PositiveIntegerField(default=7, help_text='Number of doses to prepare', verbose_name='剂数')),
                ('decoction_method', models.TextField(default='水煎服，每日一剂，分两次温服。', help_text='Instructions for decoction', verbose_name='煎煮方法')),
                ('dietary_advice', models.TextField(blank=True, verbose_name='饮食宜忌')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='生活建议')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('dispensed', '已配药'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_prescriptions', to='prescriptions.classicformula', verbose_name='基于方剂')),
                ('diagnosis_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='diagnosis.diagnosissession', verbose_name='诊断记录')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='患者')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='医师')),
            ],
            options={
                'verbose_name': '处方',
                'verbose_name_plural': '处方',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='FormulaHerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('monarch', '君药 | Monarch'), ('minister', '臣药 | Minister'), ('assistant', '佐药 | Assistant'), ('envoy', '使药 | Envoy')], default='assistant', max_length=20, verbose_name='药物角色')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='剂量')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_herbs', to='prescriptions.classicformula')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_uses', to='prescriptions.herb')),
            ],
            options={
                'verbose_name': '方剂药物',
                'verbose_name_plural': '方剂药物',
                'ordering': ['role', 'herb__name_cn'],
                'unique_together': {('formula', 'herb')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='剂量 (克)')),
                ('preparation', models.CharField(blank=True, help_text='e.g., 先煎, 后下, 包煎', max_length=100, verbose_name='炮制方法')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='prescriptions.herb', verbose_name='药材')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='处方')),
            ],
            options={
                'verbose_name': '处方药物',
                'verbose_name_plural': '处方药物',
                'ordering': ['sequence', 'herb__name_cn'],
                'unique_together': {('prescription', 'herb')},
            },
        ),
    ]
