# Generated by Django 5.2.8 on 2025-11-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('name_cn', models.CharField(max_length=200, verbose_name='中文名 | Chinese Name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名 | English Name')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='生产厂家 | Manufacturer')),
                ('approval_number', models.CharField(blank=True, help_text='国药准字号', max_length=100, verbose_name='批准文号 | Approval Number')),
                ('dosage_form', models.CharField(choices=[('pill', '丸剂 | Pills'), ('tablet', '片剂 | Tablets'), ('capsule', '胶囊 | Capsules'), ('granule', '颗粒 | Granules'), ('powder', '散剂 | Powder'), ('oral_liquid', '口服液 | Oral Liquid'), ('syrup', '糖浆 | Syrup'), ('injection', '注射液 | Injection'), ('external', '外用 | External Use')], default='tablet', max_length=20, verbose_name='剂型 | Dosage Form')),
                ('prescription_type', models.CharField(choices=[('otc', '非处方药 | OTC'), ('rx', '处方药 | Prescription')], default='otc', max_length=10, verbose_name='处方类型 | Prescription Type')),
                ('ingredients', models.TextField(help_text='主要药物成分', verbose_name='成分 | Ingredients')),
                ('functions', models.TextField(help_text='功效和适应症', verbose_name='功能主治 | Functions & Indications')),
                ('tcm_pattern', models.CharField(blank=True, help_text='适用的中医证型', max_length=200, verbose_name='中医证型 | TCM Pattern')),
                ('specification', models.CharField(help_text='例如: 0.3g×12粒×3板', max_length=100, verbose_name='规格 | Specification')),
                ('dosage_adult', models.CharField(help_text='例如: 每次4粒，每日3次', max_length=200, verbose_name='成人用量 | Adult Dosage')),
                ('dosage_child', models.CharField(blank=True, max_length=200, verbose_name='儿童用量 | Child Dosage')),
                ('administration_method', models.CharField(default='温水送服', help_text='例如: 温水送服、饭前服用等', max_length=200, verbose_name='服用方法 | Administration')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌 | Contraindications')),
                ('precautions', models.TextField(blank=True, verbose_name='注意事项 | Precautions')),
                ('adverse_reactions', models.TextField(blank=True, verbose_name='不良反应 | Adverse Reactions')),
                ('drug_interactions', models.TextField(blank=True, verbose_name='药物相互作用 | Drug Interactions')),
                ('price_per_box', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='单价 (每盒) | Price per Box')),
                ('storage_conditions', models.CharField(default='密封，置阴凉干燥处', max_length=200, verbose_name='贮藏 | Storage')),
                ('shelf_life', models.CharField(default='24个月', max_length=50, verbose_name='有效期 | Shelf Life')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='有库存 | In Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '中成药 | Patent Medicine',
                'verbose_name_plural': '中成药 | Patent Medicines',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionPatentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='盒数或瓶数', verbose_name='数量 | Quantity')),
                ('dosage_instruction', models.CharField(blank=True, help_text='可覆盖默认用量', max_length=200, verbose_name='用法用量 | Dosage Instruction')),
                ('duration_days', models.PositiveIntegerField(default=7, verbose_name='疗程天数 | Duration (days)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注 | Notes')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='顺序 | Sequence')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='prescriptions.patentmedicine', verbose_name='中成药 | Patent Medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_medicine_items', to='prescriptions.prescription', verbose_name='处方 | Prescription')),
            ],
            options={
                'verbose_name': '处方中成药 | Prescription Patent Medicine',
                'verbose_name_plural': '处方中成药 | Prescription Patent Medicines',
                'ordering': ['sequence', 'medicine__name_cn'],
                'unique_together': {('prescription', 'medicine')},
            },
        ),
    ]
