# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_patentmedicine_prescriptionpatentmedicine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoctionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称 | Chinese Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称 | English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('description', models.TextField(help_text='详细的煎药方法说明', verbose_name='描述 | Description')),
                ('water_amount', models.CharField(blank=True, help_text='例如：加水至药面上2-3厘米', max_length=100, verbose_name='加水量 | Water Amount')),
                ('soaking_time', models.CharField(blank=True, help_text='例如：浸泡20-30分钟', max_length=100, verbose_name='浸泡时间 | Soaking Time')),
                ('first_decoction', models.CharField(blank=True, help_text='例如：大火煮沸后转小火煎煮30分钟', max_length=200, verbose_name='头煎 | First Decoction')),
                ('second_decoction', models.CharField(blank=True, help_text='例如：再加水煎煮20分钟', max_length=200, verbose_name='二煎 | Second Decoction')),
                ('administration', models.CharField(blank=True, help_text='例如：混合两次煎液，分早晚两次温服', max_length=200, verbose_name='服用方法 | Administration')),
                ('special_handling', models.TextField(blank=True, help_text='需要先煎、后下、包煎等特殊处理的说明', verbose_name='特殊处理 | Special Handling')),
                ('storage_instructions', models.CharField(blank=True, help_text='例如：冷藏保存，24小时内服用', max_length=200, verbose_name='储存说明 | Storage Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '煎药方法 | Decoction Method',
                'verbose_name_plural': '煎药方法 | Decoction Methods',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=200, verbose_name='模板名称(中文) | Template Name (Chinese)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='模板名称(英文) | Template Name (English)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('category', models.CharField(blank=True, help_text='例如：感冒、咳嗽、失眠等', max_length=100, verbose_name='类别 | Category')),
                ('description', models.TextField(blank=True, verbose_name='描述 | Description')),
                ('indications', models.TextField(blank=True, verbose_name='适应症 | Indications')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌症 | Contraindications')),
                ('default_doses', models.IntegerField(default=7, verbose_name='默认剂数 | Default Doses')),
                ('modification_notes', models.TextField(blank=True, help_text='常见的加减变化', verbose_name='加减说明 | Modification Notes')),
                ('usage_notes', models.TextField(blank=True, verbose_name='使用说明 | Usage Notes')),
                ('is_public', models.BooleanField(default=False, help_text='公开模板可被所有医师使用', verbose_name='公开模板 | Public Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='prescriptions.classicformula', verbose_name='基于方剂 | Based on Formula')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者 | Created By')),
                ('default_decoction_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='prescriptions.decoctionmethod', verbose_name='默认煎药方法 | Default Decoction Method')),
            ],
            options={
                'verbose_name': '处方模板 | Prescription Template',
                'verbose_name_plural': '处方模板 | Prescription Templates',
                'ordering': ['category', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='剂量(克) | Dosage (g)')),
                ('preparation', models.CharField(blank=True, help_text='例如：先煎、后下、包煎', max_length=100, verbose_name='炮制方法 | Preparation')),
                ('is_optional', models.BooleanField(default=False, help_text='标记为可选的药物可以根据症状选择性添加', verbose_name='可选药物 | Optional')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注 | Notes')),
                ('sequence', models.IntegerField(default=0, verbose_name='顺序 | Sequence')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='prescriptions.herb', verbose_name='药材 | Herb')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescriptiontemplate', verbose_name='模板 | Template')),
            ],
            options={
                'verbose_name': '模板药物 | Template Item',
                'verbose_name_plural': '模板药物 | Template Items',
                'ordering': ['sequence', 'herb__name_cn'],
                'unique_together': {('template', 'herb')},
            },
        ),
    ]
