# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acupuncture', '0002_acupuncturesession_ai_confidence_score_and_more'),
        ('cupping', '0001_initial'),
        ('patients', '0002_medicalhistorytimeline'),
        ('prescriptions', '0003_decoctionmethod_prescriptiontemplate_and_more'),
        ('tuina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=50, unique=True, verbose_name='疗程编号 | Course Number')),
                ('course_name', models.CharField(help_text='例如：颈椎病综合治疗疗程', max_length=200, verbose_name='疗程名称 | Course Name')),
                ('primary_diagnosis', models.TextField(verbose_name='主要诊断 | Primary Diagnosis')),
                ('treatment_goal', models.TextField(help_text='疗程的预期治疗目标', verbose_name='治疗目标 | Treatment Goal')),
                ('treatment_plan', models.TextField(help_text='详细的治疗计划和方案', verbose_name='治疗方案 | Treatment Plan')),
                ('start_date', models.DateField(verbose_name='开始日期 | Start Date')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期 | Planned End Date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期 | Actual End Date')),
                ('planned_sessions_total', models.IntegerField(default=10, verbose_name='计划总次数 | Planned Total Sessions')),
                ('planned_frequency', models.CharField(blank=True, help_text='例如：每周2-3次', max_length=100, verbose_name='计划频率 | Planned Frequency')),
                ('includes_herbal_medicine', models.BooleanField(default=False, verbose_name='包含中药 | Includes Herbal Medicine')),
                ('includes_acupuncture', models.BooleanField(default=False, verbose_name='包含针灸 | Includes Acupuncture')),
                ('includes_cupping', models.BooleanField(default=False, verbose_name='包含拔罐 | Includes Cupping')),
                ('includes_tuina', models.BooleanField(default=False, verbose_name='包含推拿 | Includes Tuina')),
                ('other_treatments', models.CharField(blank=True, max_length=200, verbose_name='其他治疗 | Other Treatments')),
                ('status', models.CharField(choices=[('planned', '计划中 | Planned'), ('active', '进行中 | Active'), ('paused', '暂停 | Paused'), ('completed', '已完成 | Completed'), ('cancelled', '已取消 | Cancelled')], default='planned', max_length=20, verbose_name='状态 | Status')),
                ('progress_notes', models.TextField(blank=True, verbose_name='进展备注 | Progress Notes')),
                ('outcome_assessment', models.TextField(blank=True, verbose_name='疗效评估 | Outcome Assessment')),
                ('patient_satisfaction', models.IntegerField(blank=True, help_text='1-10分，10分最满意', null=True, verbose_name='患者满意度 | Patient Satisfaction')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估费用 | Estimated Cost')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际费用 | Actual Cost')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_courses', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_courses', to=settings.AUTH_USER_MODEL, verbose_name='主治医师 | Primary Practitioner')),
            ],
            options={
                'verbose_name': '治疗疗程 | Treatment Course',
                'verbose_name_plural': '治疗疗程 | Treatment Courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='在疗程中的第几次治疗', verbose_name='第几次 | Session Number')),
                ('session_type', models.CharField(choices=[('herbal', '中药 | Herbal Medicine'), ('acupuncture', '针灸 | Acupuncture'), ('cupping', '拔罐 | Cupping'), ('tuina', '推拿 | Tuina'), ('consultation', '咨询 | Consultation'), ('assessment', '评估 | Assessment'), ('other', '其他 | Other')], max_length=20, verbose_name='治疗类型 | Session Type')),
                ('scheduled_date', models.DateTimeField(verbose_name='预约时间 | Scheduled Date')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='实际治疗时间 | Actual Date')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主诉 | Chief Complaint')),
                ('session_notes', models.TextField(blank=True, verbose_name='治疗记录 | Session Notes')),
                ('patient_response', models.TextField(blank=True, verbose_name='患者反应 | Patient Response')),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='1-5分，5分效果最好', null=True, verbose_name='疗效评分 | Effectiveness Rating')),
                ('status', models.CharField(choices=[('scheduled', '已预约 | Scheduled'), ('completed', '已完成 | Completed'), ('cancelled', '已取消 | Cancelled'), ('no_show', '缺席 | No Show')], default='scheduled', max_length=20, verbose_name='状态 | Status')),
                ('session_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用 | Cost')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acupuncture_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to='acupuncture.acupuncturesession', verbose_name='针灸记录 | Acupuncture Session')),
                ('cupping_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to='cupping.cuppingsession', verbose_name='拔罐记录 | Cupping Session')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to='prescriptions.prescription', verbose_name='处方 | Prescription')),
                ('tuina_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to='tuina.tuinasession', verbose_name='推拿记录 | Tuina Session')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatment_course.treatmentcourse', verbose_name='疗程 | Course')),
            ],
            options={
                'verbose_name': '疗程治疗记录 | Course Session',
                'verbose_name_plural': '疗程治疗记录 | Course Sessions',
                'ordering': ['course', 'session_number'],
                'unique_together': {('course', 'session_number')},
            },
        ),
    ]
