# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('patients', '0002_medicalhistorytimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称 | Chinese Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称 | English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('description', models.TextField(blank=True, verbose_name='描述 | Description')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='时长(分钟) | Duration (minutes)')),
                ('color_code', models.CharField(default='#007bff', help_text='十六进制颜色代码，如 #007bff', max_length=7, verbose_name='颜色代码 | Color Code')),
                ('requires_preparation', models.BooleanField(default=False, verbose_name='需要准备 | Requires Preparation')),
                ('preparation_notes', models.TextField(blank=True, help_text='患者需要提前准备的事项', verbose_name='准备事项 | Preparation Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '预约类型 | Appointment Type',
                'verbose_name_plural': '预约类型 | Appointment Types',
                'ordering': ['name_cn'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(max_length=50, unique=True, verbose_name='预约编号 | Appointment Number')),
                ('appointment_date', models.DateField(verbose_name='预约日期 | Appointment Date')),
                ('start_time', models.TimeField(verbose_name='开始时间 | Start Time')),
                ('end_time', models.TimeField(verbose_name='结束时间 | End Time')),
                ('reason', models.TextField(blank=True, verbose_name='就诊原因 | Reason for Visit')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主诉 | Chief Complaint')),
                ('status', models.CharField(choices=[('pending', '待确认 | Pending'), ('confirmed', '已确认 | Confirmed'), ('arrived', '已到达 | Arrived'), ('in_progress', '进行中 | In Progress'), ('completed', '已完成 | Completed'), ('cancelled', '已取消 | Cancelled'), ('no_show', '缺席 | No Show')], default='pending', max_length=20, verbose_name='状态 | Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间 | Confirmed At')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='到达时间 | Arrival Time')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间 | Cancelled At')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('patient_request', '患者要求 | Patient Request'), ('practitioner_unavailable', '医师不可用 | Practitioner Unavailable'), ('emergency', '紧急情况 | Emergency'), ('weather', '天气原因 | Weather'), ('other', '其他 | Other')], max_length=30, verbose_name='取消原因 | Cancellation Reason')),
                ('cancellation_notes', models.TextField(blank=True, verbose_name='取消备注 | Cancellation Notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='已发送提醒 | Reminder Sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='提醒发送时间 | Reminder Sent At')),
                ('is_followup', models.BooleanField(default=False, verbose_name='复诊 | Is Follow-up')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='确认人 | Confirmed By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人 | Created By')),
                ('diagnosis_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='diagnosis.diagnosissession', verbose_name='诊断记录 | Diagnosis Session')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
                ('previous_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_appointments', to='appointments.appointment', verbose_name='上次预约 | Previous Appointment')),
                ('appointment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmenttype', verbose_name='预约类型 | Appointment Type')),
            ],
            options={
                'verbose_name': '预约 | Appointment',
                'verbose_name_plural': '预约 | Appointments',
                'ordering': ['-appointment_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, '星期一 | Monday'), (2, '星期二 | Tuesday'), (3, '星期三 | Wednesday'), (4, '星期四 | Thursday'), (5, '星期五 | Friday'), (6, '星期六 | Saturday'), (7, '星期日 | Sunday')], verbose_name='星期 | Day of Week')),
                ('start_time', models.TimeField(verbose_name='开始时间 | Start Time')),
                ('end_time', models.TimeField(verbose_name='结束时间 | End Time')),
                ('slot_duration_minutes', models.IntegerField(default=30, help_text='预约时间段的长度', verbose_name='时间段时长(分钟) | Slot Duration (minutes)')),
                ('max_appointments_per_slot', models.IntegerField(default=1, verbose_name='每时段最大预约数 | Max Appointments per Slot')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日期 | Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期 | Effective To')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
            ],
            options={
                'verbose_name': '医师排班 | Practitioner Schedule',
                'verbose_name_plural': '医师排班 | Practitioner Schedules',
                'ordering': ['practitioner', 'day_of_week', 'start_time'],
            },
        ),
    ]
