# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_medicalhistorytimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=50, unique=True, verbose_name='中文名称 | Chinese Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称 | English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('description', models.TextField(help_text='详细描述体质特点 | Detailed description of constitution characteristics', verbose_name='描述 | Description')),
                ('physical_features', models.TextField(blank=True, verbose_name='形体特征 | Physical Features')),
                ('common_symptoms', models.TextField(blank=True, verbose_name='常见表现 | Common Symptoms')),
                ('psychological_features', models.TextField(blank=True, verbose_name='心理特征 | Psychological Features')),
                ('disease_susceptibility', models.TextField(blank=True, verbose_name='易患疾病 | Disease Susceptibility')),
                ('environmental_adaptation', models.TextField(blank=True, verbose_name='环境适应性 | Environmental Adaptation')),
                ('dietary_recommendations', models.TextField(blank=True, verbose_name='饮食建议 | Dietary Recommendations')),
                ('lifestyle_recommendations', models.TextField(blank=True, verbose_name='生活起居建议 | Lifestyle Recommendations')),
                ('exercise_recommendations', models.TextField(blank=True, verbose_name='运动建议 | Exercise Recommendations')),
                ('herbal_recommendations', models.TextField(blank=True, verbose_name='药膳建议 | Herbal Food Therapy')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序 | Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '体质类型 | Constitution Type',
                'verbose_name_plural': '体质类型 | Constitution Types',
                'ordering': ['display_order', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='ConstitutionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True, verbose_name='评估日期 | Assessment Date')),
                ('primary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='主要体质得分 | Primary Score')),
                ('secondary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='次要体质得分 | Secondary Score')),
                ('scores', models.JSONField(default=dict, help_text='存储9种体质的得分 | Stores scores for all 9 constitution types', verbose_name='各体质得分 | All Constitution Scores')),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated constitution analysis and recommendations', verbose_name='AI分析 | AI Analysis')),
                ('practitioner_notes', models.TextField(blank=True, verbose_name='医师备注 | Practitioner Notes')),
                ('health_recommendations', models.TextField(blank=True, verbose_name='健康建议 | Health Recommendations')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='复评日期 | Follow-up Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitution_assessments', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constitution_assessments', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
                ('primary_constitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assessments', to='constitution.constitutiontype', verbose_name='主要体质 | Primary Constitution')),
                ('secondary_constitution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_assessments', to='constitution.constitutiontype', verbose_name='次要体质 | Secondary Constitution')),
            ],
            options={
                'verbose_name': '体质评估 | Constitution Assessment',
                'verbose_name_plural': '体质评估 | Constitution Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ConstitutionQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题 | Question')),
                ('question_number', models.IntegerField(verbose_name='题号 | Question Number')),
                ('scoring_guide', models.JSONField(blank=True, default=dict, help_text='得分说明：1=没有(不会), 2=很少, 3=有时, 4=经常, 5=总是', verbose_name='评分指南 | Scoring Guide')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constitution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='constitution.constitutiontype', verbose_name='体质类型 | Constitution Type')),
            ],
            options={
                'verbose_name': '体质问卷题目 | Constitution Question',
                'verbose_name_plural': '体质问卷题目 | Constitution Questions',
                'ordering': ['constitution_type', 'question_number'],
                'unique_together': {('constitution_type', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ConstitutionAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='1=没有, 2=很少, 3=有时, 4=经常, 5=总是', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='得分 | Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='constitution.constitutionassessment', verbose_name='评估 | Assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='constitution.constitutionquestionnaire', verbose_name='问题 | Question')),
            ],
            options={
                'verbose_name': '问卷答案 | Assessment Answer',
                'verbose_name_plural': '问卷答案 | Assessment Answers',
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
