# Generated by Django 5.2.8 on 2025-11-22 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcupunctureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='治疗日期 | Session Date')),
                ('treatment_type', models.CharField(choices=[('traditional', '传统针灸 | Traditional Acupuncture'), ('electro', '电针 | Electroacupuncture'), ('auricular', '耳针 | Auricular Acupuncture'), ('scalp', '头针 | Scalp Acupuncture'), ('moxibustion', '艾灸 | Moxibustion'), ('cupping', '拔罐 | Cupping Therapy')], default='traditional', max_length=20, verbose_name='治疗类型 | Treatment Type')),
                ('chief_complaint', models.TextField(help_text='患者主要不适症状 | Main symptoms patient is experiencing', verbose_name='主诉 | Chief Complaint')),
                ('tcm_diagnosis', models.TextField(help_text='中医辨证诊断结果 | TCM pattern differentiation diagnosis', verbose_name='中医诊断 | TCM Diagnosis')),
                ('acupoints_used', models.TextField(help_text='例如：合谷(LI4), 太冲(LR3), 足三里(ST36) | e.g., Hegu (LI4), Taichong (LR3), Zusanli (ST36)', verbose_name='使用穴位 | Acupoints Used')),
                ('needle_retention_time', models.CharField(choices=[('15min', '15分钟 | 15 minutes'), ('20min', '20分钟 | 20 minutes'), ('30min', '30分钟 | 30 minutes'), ('40min', '40分钟 | 40 minutes')], default='30min', max_length=10, verbose_name='留针时间 | Needle Retention Time')),
                ('technique_notes', models.TextField(blank=True, help_text='针刺手法、深度、刺激强度等 | Needling technique, depth, stimulation intensity, etc.', verbose_name='手法说明 | Technique Notes')),
                ('used_moxibustion', models.BooleanField(default=False, verbose_name='配合艾灸 | Used Moxibustion')),
                ('used_cupping', models.BooleanField(default=False, verbose_name='配合拔罐 | Used Cupping')),
                ('used_tuina', models.BooleanField(default=False, verbose_name='配合推拿 | Used Tuina Massage')),
                ('patient_response', models.CharField(blank=True, choices=[('excellent', '效果显著 | Excellent'), ('good', '效果良好 | Good'), ('fair', '效果一般 | Fair'), ('poor', '效果不佳 | Poor'), ('no_change', '无明显变化 | No Change')], max_length=20, verbose_name='患者反应 | Patient Response')),
                ('treatment_notes', models.TextField(blank=True, help_text='患者感受、注意事项、建议等 | Patient feedback, precautions, recommendations, etc.', verbose_name='治疗备注 | Treatment Notes')),
                ('next_session_date', models.DateField(blank=True, null=True, verbose_name='下次复诊日期 | Next Session Date')),
                ('treatment_plan', models.TextField(blank=True, help_text='后续治疗计划和建议 | Follow-up treatment plan and recommendations', verbose_name='治疗计划 | Treatment Plan')),
                ('session_fee', models.DecimalField(blank=True, decimal_places=2, help_text='马币 | MYR', max_digits=10, null=True, verbose_name='治疗费用 | Session Fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间 | Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间 | Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃 | Active')),
                ('assigned_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acupuncture_sessions', to=settings.AUTH_USER_MODEL, verbose_name='负责医师 | Assigned Practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acupuncture_sessions', to='patients.patient', verbose_name='患者 | Patient')),
            ],
            options={
                'verbose_name': '针灸治疗 | Acupuncture Session',
                'verbose_name_plural': '针灸治疗记录 | Acupuncture Sessions',
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['-session_date', '-created_at'], name='acupuncture_session_1d7eed_idx'), models.Index(fields=['patient', '-session_date'], name='acupuncture_patient_4b4b28_idx')],
            },
        ),
    ]
