# Generated by Django 5.2.8 on 2025-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acupuncture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acupuncturesession',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI建议的置信度 (0-100) | Confidence level of AI suggestion (0-100)', max_digits=5, null=True, verbose_name='AI置信度 | AI Confidence Score'),
        ),
        migrations.AddField(
            model_name='acupuncturesession',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='AI推荐的理论依据 | Theoretical basis for AI recommendation', verbose_name='AI推理依据 | AI Reasoning'),
        ),
        migrations.AddField(
            model_name='acupuncturesession',
            name='ai_recommendation_used',
            field=models.BooleanField(default=False, help_text='是否采用了AI建议的穴位 | Whether AI-suggested acupoints were used', verbose_name='采用AI建议 | Used AI Recommendation'),
        ),
        migrations.AddField(
            model_name='acupuncturesession',
            name='ai_suggested_acupoints',
            field=models.TextField(blank=True, help_text='基于症状的AI推荐穴位 | AI-recommended acupoints based on symptoms', verbose_name='AI建议穴位 | AI Suggested Acupoints'),
        ),
        migrations.AlterField(
            model_name='acupuncturesession',
            name='treatment_type',
            field=models.CharField(choices=[('traditional', '传统针灸 | Traditional Acupuncture'), ('electro', '电针 | Electroacupuncture'), ('auricular', '耳针 | Auricular Acupuncture'), ('scalp', '头针 | Scalp Acupuncture'), ('moxibustion', '艾灸 | Moxibustion'), ('cupping', '拔罐 | Cupping Therapy'), ('laser', '激光针灸 | Laser Acupuncture'), ('magnetic', '磁疗针灸 | Magnetic Acupuncture'), ('warming', '温针灸 | Warming Needle'), ('fire_needle', '火针 | Fire Needling'), ('bloodletting', '刺络放血 | Bloodletting Therapy')], default='traditional', max_length=20, verbose_name='治疗类型 | Treatment Type'),
        ),
        migrations.CreateModel(
            name='AcupointReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例如：LI4, ST36 | e.g., LI4, ST36', max_length=10, unique=True, verbose_name='穴位编码 | Acupoint Code')),
                ('chinese_name', models.CharField(help_text='例如：合谷 | e.g., Hegu', max_length=50, verbose_name='中文名称 | Chinese Name')),
                ('pinyin_name', models.CharField(help_text='例如：Hegu | e.g., Hegu', max_length=50, verbose_name='拼音名称 | Pinyin Name')),
                ('english_name', models.CharField(blank=True, help_text='例如：Union Valley | e.g., Union Valley', max_length=100, verbose_name='英文名称 | English Name')),
                ('meridian', models.CharField(choices=[('LU', '手太阴肺经 | Lung Meridian'), ('LI', '手阳明大肠经 | Large Intestine Meridian'), ('ST', '足阳明胃经 | Stomach Meridian'), ('SP', '足太阴脾经 | Spleen Meridian'), ('HT', '手少阴心经 | Heart Meridian'), ('SI', '手太阳小肠经 | Small Intestine Meridian'), ('BL', '足太阳膀胱经 | Bladder Meridian'), ('KI', '足少阴肾经 | Kidney Meridian'), ('PC', '手厥阴心包经 | Pericardium Meridian'), ('TB', '手少阳三焦经 | Triple Burner Meridian'), ('GB', '足少阳胆经 | Gallbladder Meridian'), ('LR', '足厥阴肝经 | Liver Meridian'), ('GV', '督脉 | Governing Vessel'), ('CV', '任脉 | Conception Vessel'), ('EX', '经外奇穴 | Extra Points')], max_length=2, verbose_name='所属经络 | Meridian')),
                ('location_chinese', models.TextField(help_text='穴位的精确位置描述 | Precise location description', verbose_name='定位（中文）| Location (Chinese)')),
                ('location_english', models.TextField(blank=True, verbose_name='定位（英文）| Location (English)')),
                ('image_2d', models.ImageField(blank=True, help_text='穴位2D示意图 | 2D illustration of acupoint', null=True, upload_to='acupoints/2d/', verbose_name='2D图片 | 2D Image')),
                ('image_3d', models.ImageField(blank=True, help_text='穴位3D示意图 | 3D illustration of acupoint', null=True, upload_to='acupoints/3d/', verbose_name='3D图片 | 3D Image')),
                ('video_url', models.URLField(blank=True, help_text='穴位演示视频URL | Demonstration video URL', verbose_name='视频链接 | Video URL')),
                ('indications', models.TextField(help_text='主治病症 | Main indications for treatment', verbose_name='主治 | Indications')),
                ('functions', models.TextField(help_text='穴位功效 | Therapeutic functions', verbose_name='功效 | Functions')),
                ('techniques', models.TextField(blank=True, help_text='进针深度、角度、手法 | Needle depth, angle, manipulation', verbose_name='针刺方法 | Needling Techniques')),
                ('precautions', models.TextField(blank=True, help_text='禁忌症和注意事项 | Contraindications and precautions', verbose_name='注意事项 | Precautions')),
                ('usage_count', models.IntegerField(default=0, help_text='在系统中被使用的次数 | Times used in the system', verbose_name='使用次数 | Usage Count')),
                ('effectiveness_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='基于治疗反馈的有效率 | Effectiveness based on treatment feedback', max_digits=4, verbose_name='有效率 | Effectiveness Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间 | Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间 | Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃 | Active')),
            ],
            options={
                'verbose_name': '穴位参考 | Acupoint Reference',
                'verbose_name_plural': '穴位参考库 | Acupoint Reference Library',
                'ordering': ['meridian', 'code'],
                'indexes': [models.Index(fields=['code'], name='acupuncture_code_2eb882_idx'), models.Index(fields=['meridian'], name='acupuncture_meridia_59f509_idx'), models.Index(fields=['-usage_count'], name='acupuncture_usage_c_859775_idx')],
            },
        ),
    ]
