# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_medicalhistorytimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuinaTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=50, verbose_name='中文名称 | Chinese Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称 | English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码 | Code')),
                ('category', models.CharField(blank=True, help_text='例如：摆动类、摩擦类、挤压类、振动类等', max_length=50, verbose_name='类别 | Category')),
                ('description', models.TextField(blank=True, verbose_name='描述 | Description')),
                ('method', models.TextField(blank=True, help_text='详细操作步骤和要领 | Detailed operation steps and key points', verbose_name='操作方法 | Method')),
                ('key_points', models.TextField(blank=True, verbose_name='操作要领 | Key Points')),
                ('functions', models.TextField(blank=True, verbose_name='功效 | Functions')),
                ('indications', models.TextField(blank=True, verbose_name='适应症 | Indications')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌症 | Contraindications')),
                ('common_areas', models.TextField(blank=True, verbose_name='常用部位 | Common Areas')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '推拿手法 | Tuina Technique',
                'verbose_name_plural': '推拿手法 | Tuina Techniques',
                'ordering': ['category', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='TuinaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(verbose_name='治疗日期 | Session Date')),
                ('chief_complaint', models.TextField(verbose_name='主诉 | Chief Complaint')),
                ('tcm_diagnosis', models.TextField(blank=True, verbose_name='中医诊断 | TCM Diagnosis')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='治则 | Treatment Principle')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='治疗时长(分钟) | Duration (minutes)')),
                ('treatment_areas', models.JSONField(default=list, help_text='治疗的身体部位列表 | List of body areas treated', verbose_name='治疗部位 | Treatment Areas')),
                ('primary_focus', models.CharField(blank=True, help_text='例如：颈椎病、腰痛、肩周炎等', max_length=200, verbose_name='主要治疗重点 | Primary Focus')),
                ('pain_level_before', models.IntegerField(blank=True, help_text='0-10级，0=无痛，10=剧痛', null=True, verbose_name='治疗前疼痛等级 | Pain Level Before')),
                ('pain_level_after', models.IntegerField(blank=True, help_text='0-10级', null=True, verbose_name='治疗后疼痛等级 | Pain Level After')),
                ('mobility_before', models.CharField(blank=True, max_length=200, verbose_name='治疗前活动度 | Mobility Before')),
                ('mobility_after', models.CharField(blank=True, max_length=200, verbose_name='治疗后活动度 | Mobility After')),
                ('patient_sensation', models.TextField(blank=True, help_text='治疗过程中和治疗后的感受', verbose_name='患者感受 | Patient Sensation')),
                ('immediate_effect', models.TextField(blank=True, verbose_name='即时效果 | Immediate Effect')),
                ('home_exercises', models.TextField(blank=True, help_text='建议患者在家进行的练习', verbose_name='家庭练习 | Home Exercises')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='生活建议 | Lifestyle Advice')),
                ('next_session_date', models.DateField(blank=True, null=True, verbose_name='下次治疗日期 | Next Session Date')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件 | Attachments')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuina_sessions', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuina_sessions', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
            ],
            options={
                'verbose_name': '推拿记录 | Tuina Session',
                'verbose_name_plural': '推拿记录 | Tuina Sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='TuinaSessionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_area', models.CharField(help_text='例如：颈部、肩部、腰部、背部等', max_length=100, verbose_name='治疗部位 | Body Area')),
                ('duration_minutes', models.IntegerField(default=5, verbose_name='时长(分钟) | Duration (minutes)')),
                ('intensity', models.CharField(blank=True, help_text='例如：轻、中、重', max_length=50, verbose_name='力度 | Intensity')),
                ('repetitions', models.IntegerField(blank=True, null=True, verbose_name='重复次数 | Repetitions')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注 | Notes')),
                ('sequence', models.IntegerField(default=0, verbose_name='顺序 | Sequence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques_used', to='tuina.tuinasession', verbose_name='治疗记录 | Session')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_uses', to='tuina.tuinatechnique', verbose_name='手法 | Technique')),
            ],
            options={
                'verbose_name': '治疗手法记录 | Session Technique',
                'verbose_name_plural': '治疗手法记录 | Session Techniques',
                'ordering': ['sequence', 'technique'],
            },
        ),
    ]
