# Generated by Django 5.2.8 on 2025-11-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked_date",
                    models.DateField(verbose_name="不可预约日期 | Blocked Date"),
                ),
                (
                    "reason_cn",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="原因（中文） | Reason (Chinese)",
                    ),
                ),
                (
                    "reason_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="原因（英文） | Reason (English)",
                    ),
                ),
                (
                    "is_full_day",
                    models.BooleanField(default=True, verbose_name="全天 | Full Day"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="部分时间段不可用时填写 | Fill when partial time block",
                        null=True,
                        verbose_name="开始时间 | Start Time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="部分时间段不可用时填写 | Fill when partial time block",
                        null=True,
                        verbose_name="结束时间 | End Time",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="留空表示诊所休息 | Leave blank for clinic closure",
                        limit_choices_to={"role": "practitioner"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="医师 | Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "不可预约日期 | Blocked Date",
                "verbose_name_plural": "不可预约日期 | Blocked Dates",
                "ordering": ["-blocked_date"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "周一 | Monday"),
                            (1, "周二 | Tuesday"),
                            (2, "周三 | Wednesday"),
                            (3, "周四 | Thursday"),
                            (4, "周五 | Friday"),
                            (5, "周六 | Saturday"),
                            (6, "周日 | Sunday"),
                        ],
                        verbose_name="星期 | Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="开始时间 | Start Time")),
                ("end_time", models.TimeField(verbose_name="结束时间 | End Time")),
                (
                    "slot_duration",
                    models.IntegerField(
                        default=30,
                        help_text="每个预约时段的长度 | Length of each appointment slot",
                        verbose_name="时段时长（分钟） | Slot Duration (Minutes)",
                    ),
                ),
                (
                    "max_appointments",
                    models.IntegerField(
                        default=1,
                        help_text="该时段最多可预约人数 | Maximum number of appointments for this slot",
                        verbose_name="最大预约数 | Max Appointments",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="留空表示适用于所有医师 | Leave blank for all practitioners",
                        limit_choices_to={"role": "practitioner"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="医师 | Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "可用时间段 | Time Slot",
                "verbose_name_plural": "可用时间段 | Time Slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="预约号 | Appointment Number",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("internal_medicine", "中医内科 | Internal Medicine"),
                            ("acupuncture", "针灸治疗 | Acupuncture"),
                            ("tuina", "推拿按摩 | Tuina Massage"),
                            ("herbal_consultation", "中药咨询 | Herbal Consultation"),
                            ("health_assessment", "健康评估 | Health Assessment"),
                            ("follow_up", "复诊 | Follow-up"),
                            ("other", "其他 | Other"),
                        ],
                        default="internal_medicine",
                        max_length=50,
                        verbose_name="服务类型 | Service Type",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(verbose_name="预约日期 | Appointment Date"),
                ),
                (
                    "appointment_time",
                    models.TimeField(verbose_name="预约时间 | Appointment Time"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="30分钟 | 30 minutes",
                        verbose_name="预计时长（分钟） | Duration (Minutes)",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True,
                        help_text="如果患者已注册，此字段可留空 | Leave blank if patient is registered",
                        max_length=200,
                        verbose_name="患者姓名 | Patient Name",
                    ),
                ),
                (
                    "patient_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="联系电话 | Contact Phone",
                    ),
                ),
                (
                    "patient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="邮箱 | Email"
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True,
                        help_text="简述主要症状或就诊原因 | Brief description of main symptoms or reason for visit",
                        verbose_name="主诉 | Chief Complaint",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注 | Notes")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="仅医师和管理员可见 | Visible to practitioners and admins only",
                        verbose_name="内部备注 | Internal Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认 | Pending"),
                            ("confirmed", "已确认 | Confirmed"),
                            ("completed", "已完成 | Completed"),
                            ("cancelled", "已取消 | Cancelled"),
                            ("no_show", "未到诊 | No Show"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态 | Status",
                    ),
                ),
                (
                    "is_first_visit",
                    models.BooleanField(
                        default=True, verbose_name="首诊 | First Visit"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="已发送提醒 | Reminder Sent"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="提醒发送时间 | Reminder Sent At",
                    ),
                ),
                (
                    "confirmation_sent",
                    models.BooleanField(
                        default=False, verbose_name="已发送确认 | Confirmation Sent"
                    ),
                ),
                (
                    "confirmation_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="确认发送时间 | Confirmation Sent At",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取消时间 | Cancelled At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, verbose_name="取消原因 | Cancellation Reason"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用 | Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间 | Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新时间 | Updated At"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="取消人 | Cancelled By",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="患者 | Patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "practitioner"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="医师 | Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约 | Appointment",
                "verbose_name_plural": "预约 | Appointments",
                "ordering": ["-appointment_date", "-appointment_time"],
                "indexes": [
                    models.Index(
                        fields=["appointment_date", "appointment_time"],
                        name="booking_app_appoint_c82d03_idx",
                    ),
                    models.Index(
                        fields=["patient", "appointment_date"],
                        name="booking_app_patient_434b54_idx",
                    ),
                    models.Index(
                        fields=["practitioner", "appointment_date"],
                        name="booking_app_practit_a12239_idx",
                    ),
                    models.Index(
                        fields=["status"], name="booking_app_status_513784_idx"
                    ),
                ],
            },
        ),
    ]
