# Generated by Django 5.2.8 on 2025-11-18 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Symptom Code')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_cn', models.CharField(max_length=200, verbose_name='Name (Chinese)')),
                ('category', models.CharField(choices=[('general', 'General (全身)'), ('head', 'Head & Face (头面)'), ('chest', 'Chest & Abdomen (胸腹)'), ('limbs', 'Limbs (四肢)'), ('skin', 'Skin (皮肤)'), ('sleep', 'Sleep (睡眠)'), ('appetite', 'Appetite & Digestion (食欲消化)'), ('urination', 'Urination & Defecation (二便)'), ('emotion', 'Emotion (情志)'), ('gynecology', 'Gynecology (妇科)')], default='general', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Syndrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Syndrome Code')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_cn', models.CharField(max_length=200, verbose_name='Name (Chinese)')),
                ('category', models.CharField(choices=[('qi', 'Qi Patterns (气病证)'), ('blood', 'Blood Patterns (血病证)'), ('yin_yang', 'Yin-Yang Patterns (阴阳病证)'), ('fluid', 'Fluid Patterns (津液病证)'), ('organ', 'Organ Patterns (脏腑病证)'), ('exterior', 'Exterior Patterns (表证)'), ('interior', 'Interior Patterns (里证)')], default='qi', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('etiology', models.TextField(blank=True, help_text='Cause and pathogenesis', verbose_name='Etiology (病因病机)')),
                ('clinical_manifestations', models.TextField(blank=True, verbose_name='Clinical Manifestations (临床表现)')),
                ('tongue_signs', models.CharField(blank=True, max_length=200, verbose_name='Tongue Signs (舌象)')),
                ('pulse_signs', models.CharField(blank=True, max_length=200, verbose_name='Pulse Signs (脉象)')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='Treatment Principle (治则治法)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Syndrome',
                'verbose_name_plural': 'Syndromes',
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='TongueAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='Session Date')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint (主诉)')),
                ('spirit_status', models.CharField(blank=True, help_text='e.g., Alert, Listless, Agitated', max_length=100, verbose_name='Spirit Status (神)')),
                ('complexion', models.CharField(blank=True, max_length=100, verbose_name='Complexion (面色)')),
                ('tongue_body_color', models.CharField(blank=True, choices=[('pale', 'Pale (淡白)'), ('light_red', 'Light Red (淡红)'), ('red', 'Red (红)'), ('deep_red', 'Deep Red (绛红)'), ('purple', 'Purple (紫)'), ('blue', 'Blue (青)')], max_length=20, verbose_name='Tongue Body Color')),
                ('tongue_body_shape', models.CharField(blank=True, choices=[('normal', 'Normal (正常)'), ('thin', 'Thin (瘦薄)'), ('swollen', 'Swollen (胖大)'), ('teeth_marked', 'Teeth-marked (齿痕)'), ('cracked', 'Cracked (裂纹)'), ('thorny', 'Thorny (芒刺)')], max_length=20, verbose_name='Tongue Body Shape')),
                ('tongue_coating_color', models.CharField(blank=True, choices=[('white', 'White (白)'), ('yellow', 'Yellow (黄)'), ('gray', 'Gray (灰)'), ('black', 'Black (黑)')], max_length=20, verbose_name='Tongue Coating Color')),
                ('tongue_coating_texture', models.CharField(blank=True, choices=[('thin', 'Thin (薄)'), ('thick', 'Thick (厚)'), ('greasy', 'Greasy (腻)'), ('peeled', 'Peeled (剥)'), ('none', 'None (无苔)')], max_length=20, verbose_name='Tongue Coating Texture')),
                ('tongue_notes', models.TextField(blank=True, verbose_name='Additional Tongue Notes')),
                ('voice_quality', models.CharField(blank=True, max_length=100, verbose_name='Voice Quality')),
                ('breath_odor', models.CharField(blank=True, max_length=100, verbose_name='Breath Odor')),
                ('auscultation_notes', models.TextField(blank=True, verbose_name='Auscultation Notes')),
                ('selected_symptoms', models.JSONField(default=list, help_text='List of symptom codes selected during inquiry', verbose_name='Selected Symptoms')),
                ('symptom_details', models.TextField(blank=True, help_text='Duration, severity, triggering factors', verbose_name='Symptom Details')),
                ('sleep_quality', models.CharField(blank=True, max_length=100, verbose_name='Sleep Quality')),
                ('appetite', models.CharField(blank=True, max_length=100, verbose_name='Appetite')),
                ('thirst', models.CharField(blank=True, max_length=100, verbose_name='Thirst')),
                ('defecation', models.CharField(blank=True, max_length=100, verbose_name='Defecation')),
                ('urination', models.CharField(blank=True, max_length=100, verbose_name='Urination')),
                ('perspiration', models.CharField(blank=True, max_length=100, verbose_name='Perspiration')),
                ('inquiry_notes', models.TextField(blank=True, verbose_name='Additional Inquiry Notes')),
                ('pulse_left_cun', models.CharField(blank=True, max_length=50, verbose_name='Left Cun Pulse')),
                ('pulse_left_guan', models.CharField(blank=True, max_length=50, verbose_name='Left Guan Pulse')),
                ('pulse_left_chi', models.CharField(blank=True, max_length=50, verbose_name='Left Chi Pulse')),
                ('pulse_right_cun', models.CharField(blank=True, max_length=50, verbose_name='Right Cun Pulse')),
                ('pulse_right_guan', models.CharField(blank=True, max_length=50, verbose_name='Right Guan Pulse')),
                ('pulse_right_chi', models.CharField(blank=True, max_length=50, verbose_name='Right Chi Pulse')),
                ('pulse_overall', models.CharField(blank=True, max_length=100, verbose_name='Overall Pulse Quality')),
                ('palpation_notes', models.TextField(blank=True, verbose_name='Palpation Notes')),
                ('ai_suggested_syndromes', models.JSONField(default=list, help_text='List of syndrome codes with confidence scores', verbose_name='AI Suggested Syndromes')),
                ('final_diagnosis', models.TextField(blank=True, verbose_name='Final Diagnosis (辨证结论)')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='Treatment Principle (治则治法)')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_sessions', to='patients.medicalrecord', verbose_name='Medical Record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_sessions', to='patients.patient', verbose_name='Patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Practitioner')),
            ],
            options={
                'verbose_name': 'Diagnosis Session',
                'verbose_name_plural': 'Diagnosis Sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='SyndromeSysmptomWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Importance of this symptom for syndrome identification (0.1-3.0)', verbose_name='Weight')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this a primary/key symptom for this syndrome?', verbose_name='Primary Symptom')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.symptom')),
                ('syndrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.syndrome')),
            ],
            options={
                'verbose_name': 'Syndrome-Symptom Weight',
                'verbose_name_plural': 'Syndrome-Symptom Weights',
                'unique_together': {('syndrome', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='syndrome',
            name='symptoms',
            field=models.ManyToManyField(related_name='syndromes', through='diagnosis.SyndromeSysmptomWeight', to='diagnosis.symptom', verbose_name='Associated Symptoms'),
        ),
    ]
