# Generated by Django 5.2.8 on 2025-11-18 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('chinese_name', models.CharField(blank=True, max_length=100, verbose_name='Chinese Name (中文姓名)')),
                ('ic_number', models.CharField(help_text='Malaysian IC or Passport number', max_length=30, unique=True, verbose_name='IC/Passport Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male (男)'), ('F', 'Female (女)'), ('O', 'Other (其他)')], max_length=1, verbose_name='Gender')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UK', 'Unknown')], default='UK', max_length=3, verbose_name='Blood Type')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('allergies', models.TextField(blank=True, help_text='List all known allergies to medications, herbs, or substances', verbose_name='Allergies (过敏史)')),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g., Diabetes, Hypertension, Heart Disease', verbose_name='Chronic Conditions (慢性疾病)')),
                ('current_medications', models.TextField(blank=True, help_text='List all current Western and TCM medications', verbose_name='Current Medications (目前用药)')),
                ('medical_history', models.TextField(blank=True, help_text='Past surgeries, major illnesses, hospitalizations', verbose_name='Medical History (病史)')),
                ('family_history', models.TextField(blank=True, help_text='Hereditary conditions in family', verbose_name='Family History (家族史)')),
                ('tcm_constitution', models.CharField(blank=True, help_text='e.g., 气虚质, 阳虚质, 痰湿质', max_length=100, verbose_name='TCM Constitution (中医体质)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('consent_data_sharing', models.BooleanField(default=False, help_text='PDPA 2010 compliant consent for data sharing', verbose_name='Consent to Data Sharing')),
                ('consent_date', models.DateField(blank=True, null=True, verbose_name='Consent Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_practitioner', models.ForeignKey(blank=True, limit_choices_to={'role': 'practitioner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Practitioner')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('initial', 'Initial Visit (初诊)'), ('followup', 'Follow-up (复诊)'), ('emergency', 'Emergency (急诊)'), ('consultation', 'Consultation (会诊)')], default='initial', max_length=20, verbose_name='Record Type')),
                ('visit_date', models.DateTimeField(verbose_name='Visit Date')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint (主诉)')),
                ('inspection_notes', models.TextField(blank=True, help_text='Spirit, complexion, tongue, body form', verbose_name='Inspection Notes (望诊)')),
                ('tongue_diagnosis', models.TextField(blank=True, help_text='Tongue body, coating, moisture', verbose_name='Tongue Diagnosis (舌诊)')),
                ('auscultation_notes', models.TextField(blank=True, help_text='Voice, breath, odors', verbose_name='Auscultation/Olfaction Notes (闻诊)')),
                ('inquiry_notes', models.TextField(blank=True, help_text='Ten questions, symptoms history', verbose_name='Inquiry Notes (问诊)')),
                ('pulse_diagnosis', models.TextField(blank=True, help_text='Pulse qualities: rate, rhythm, strength, depth', verbose_name='Pulse Diagnosis (脉诊)')),
                ('palpation_notes', models.TextField(blank=True, help_text='Abdominal, point tenderness', verbose_name='Palpation Notes (切诊)')),
                ('tcm_diagnosis', models.TextField(blank=True, help_text='Pattern/Syndrome identification (辨证)', verbose_name='TCM Diagnosis (中医诊断)')),
                ('western_diagnosis', models.TextField(blank=True, help_text='ICD-10 codes if applicable', verbose_name='Western Diagnosis')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='Treatment Principle (治则治法)')),
                ('prescription', models.TextField(blank=True, help_text='Herbal formula with dosages', verbose_name='Prescription (处方)')),
                ('acupuncture_points', models.TextField(blank=True, verbose_name='Acupuncture Points (针灸穴位)')),
                ('other_treatments', models.TextField(blank=True, help_text='Tuina, cupping, moxibustion, etc.', verbose_name='Other Treatments')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='Lifestyle Advice (生活建议)')),
                ('dietary_advice', models.TextField(blank=True, verbose_name='Dietary Advice (饮食建议)')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Follow-up Notes')),
                ('next_appointment', models.DateTimeField(blank=True, null=True, verbose_name='Next Appointment')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file paths for images, lab results, etc.', verbose_name='Attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner', models.ForeignKey(limit_choices_to={'role': 'practitioner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-visit_date'],
            },
        ),
    ]
