# Generated by Django 5.2.8 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('diagnosis', '诊断 | Diagnosis'), ('prescription', '处方 | Prescription'), ('acupuncture', '针灸 | Acupuncture'), ('cupping', '拔罐 | Cupping'), ('tuina', '推拿 | Tuina'), ('lab_test', '检验 | Lab Test'), ('imaging', '影像 | Imaging'), ('surgery', '手术 | Surgery'), ('hospitalization', '住院 | Hospitalization'), ('allergy', '过敏反应 | Allergy Reaction'), ('vaccination', '疫苗接种 | Vaccination'), ('other', '其他 | Other')], max_length=20, verbose_name='事件类型 | Event Type')),
                ('event_date', models.DateTimeField(verbose_name='事件日期 | Event Date')),
                ('title', models.CharField(max_length=200, verbose_name='标题 | Title')),
                ('description', models.TextField(blank=True, verbose_name='描述 | Description')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型 | Related Object Type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID | Related Object ID')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要事件 | Important Event')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件 | Attachments')),
                ('notes', models.TextField(blank=True, verbose_name='备注 | Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 | Active')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patients.medicalrecord', verbose_name='医疗记录 | Medical Record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_timeline', to='patients.patient', verbose_name='患者 | Patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='医师 | Practitioner')),
            ],
            options={
                'verbose_name': '病史时间线 | Medical History Timeline',
                'verbose_name_plural': '病史时间线 | Medical History Timeline',
                'ordering': ['-event_date'],
            },
        ),
    ]
